#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ~/bin
  ~/.prygems/bin
  /opt/chef/bin
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

#
# Tools
#

# direnv
if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

# rbenv
if [[ -d ${ZDOTDIR:-$HOME}/.rbenv/bin ]]; then
  path=(${ZDOTDIR:-$HOME}/.rbenv/bin $path)
fi
if (( $+commands[rbenv] )); then
  eval "$(rbenv init - zsh)"
fi

#
# Other environment variables
#

export ERL_FLAGS="-kernel shell_history enabled"

export GOPATH=${ZDOTDIR:-$HOME}/.go
path=($GOPATH/bin $path)

if [[ -d /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/ ]]; then
  export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/
fi

if [[ -d /usr/local/opt/android-sdk ]]; then
  export ANDROID_SDK_ROOT=/usr/local/opt/android-sdk
fi

if [[ -s ${ZDOTDIR:-$HOME}/.aws/env ]]; then
  source ${ZDOTDIR:-$HOME}/.aws/env
fi

if [[ -s ${ZDOTDIR:-$HOME}/.zprofile.local ]]; then
  source ${ZDOTDIR:-$HOME}/.zprofile.local
fi
