#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ~/bin
  ~/.prygems/bin
  /opt/chef/bin
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

#
# Tools
#

# direnv
if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

# rbenv
if [[ -d ${ZDOTDIR:-$HOME}/.rbenv/bin ]]; then
  path=(${ZDOTDIR:-$HOME}/.rbenv/bin $path)
  eval "$(rbenv init - zsh)"
fi

# rvm (e.g. for nitrous.io)
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  path=(${ZDOTDIR:-$HOME}/.rvm/bin $path)
  source "$HOME/.rvm/scripts/rvm"
fi

# nvm
if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
  source "$HOME/.nvm/nvm.sh"
fi

# autoparts (for nitrous.io)
if [[ -d ${ZDOTDIR:-$HOME}/.parts/autoparts/bin ]]; then
  path=(${ZDOTDIR:-$HOME}/.parts/autoparts/bin $path)
  eval "$(parts init -)"
fi

#
# Other environment variables
#

export RUBY_GC_OLDMALLOC_LIMIT=128000000
export RUBY_GC_MALLOC_LIMIT=128000000
export RUBY_GC_HEAP_SLOTS_GROWTH_FACTOR=1.25
export RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
export RUBY_GC_HEAP_INIT_SLOTS=1600000
export RUBY_GC_HEAP_FREE_SLOTS=600000
export RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.3

if [[ -f /usr/local/opt/curl-ca-bundle/share/ca-bundle.crt ]]; then
  export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt
fi

export GOPATH=${ZDOTDIR:-$HOME}/.go
path=($GOPATH/bin $path)

if [[ -d /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/ ]]; then
  export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/
fi

if [[ -d /usr/local/opt/android-sdk ]]; then
  export ANDROID_SDK_ROOT=/usr/local/opt/android-sdk
fi

if [[ -s ${ZDOTDIR:-$HOME}/.aws/env ]]; then
  source ${ZDOTDIR:-$HOME}/.aws/env
fi

if [[ -s ${ZDOTDIR:-$HOME}/.zprofile.local ]]; then
  source ${ZDOTDIR:-$HOME}/.zprofile.local
fi
