#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ -s ${ZDOTDIR:-$HOME}/.tmuxinator/scripts/tmuxinator ]]; then
  source ${ZDOTDIR:-$HOME}/.tmuxinator/scripts/tmuxinator
fi

source ${ZDOTDIR:-$HOME}/.zsh/aliases.zsh

# Load custom function definitions from ${ZDOTDIR:-$HOME}/.zsh/functions
fpath=(${ZDOTDIR:-$HOME}/.zsh/functions $fpath)
autoload -Uz ${ZDOTDIR:-$HOME}/.zsh/functions/*(:t)
compinit -i

# autocompletion
if [[ -d /usr/local/share/zsh-completions ]]; then
  fpath=(/usr/local/share/zsh-completions $fpath)
fi

# autocompletion for aws cli
if [[ -s /usr/local/share/zsh/site-functions/_aws ]]; then
  source /usr/local/share/zsh/site-functions/_aws
fi

Code=${ZDOTDIR:-$HOME}/Code

# 100s
if [[ -d $Code/100Starlings/100s/bin ]]; then
  eval "$($Code/100Starlings/100s/bin/100s init -)"
fi

# cplus
if [[ -d $Code/CPlus/cplus/bin ]]; then
  eval "$($Code/CPlus/cplus/bin/cplus init -)"
fi

# overcommit
if (( $+commands[overcommit] )); then
  export GIT_TEMPLATE_DIR=`overcommit --template-dir`
fi

# k.sh
if [[ -s $Code/supercrabtree/k/k.sh ]]; then
  source $Code/supercrabtree/k/k.sh
fi

# asdf
if [[ -f ${ZDOTDIR:-$HOME}/.asdf/asdf.sh ]]; then
  source ${ZDOTDIR:-$HOME}/.asdf/asdf.sh
  source ${ZDOTDIR:-$HOME}/.asdf/completions/asdf.bash
fi

if [[ -s ${ZDOTDIR:-$HOME}/.zshrc.local ]]; then
  source ${ZDOTDIR:-$HOME}/.zshrc.local
fi
